# Generated by Django 4.2.5 on 2023-09-29 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker_name', models.CharField(max_length=45, null=True)),
                ('brand_name', models.CharField(max_length=45, null=True)),
                ('standard', models.IntegerField(default=1)),
                ('date_add', models.DateTimeField(null=True)),
                ('date_mod', models.DateTimeField(null=True)),
                ('id_role', models.PositiveIntegerField()),
                ('fuckingmorfology', models.CharField(max_length=45, null=True)),
                ('details', models.CharField(max_length=45, null=True)),
                ('hidden', models.IntegerField(default=0, null=True)),
                ('fps', models.IntegerField(null=True)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(null=True)),
                ('date_mod', models.DateTimeField(null=True)),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markers.marker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
